### ISSUE TITLE
Migrate realm-o-matic to silver

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1542]
### Components that need migration
- realm-o-matic frontend and backend
- realm creator (the ansible playbook)

### tasks:
- [x] request for ssl cert
- [x] create new DNS entries
- [x] oc manifest updates for ocp4
- [x] migration dev and test realm-o-matic app
- [x] migration dev and test ansible app
- [x] community notification
- [x] migration prod realm-o-matic app
- [x] migration prod ansible app
- [x] GH webhook updates for realm-o-matic app
- [x] GH webhook updates for ansible app
- [x] test out provisioning feature
- [x] remove created test realms

Extra tasks:
- [x] ansible webhook component upgrade
- [x] update ansible app with vanity route

**Comment by ShellyXueHan** [comment]
migration completed.
