### ISSUE TITLE
Create automation to reduce effort in perform application resiliency and resource usage assessment

### ISSUE THREAD

**Issue by michaelshire** [bcgov/devhub-app-web#1651]
This issue tracks the initial minimum viable product of an app assessment tool, which will be consumable by BCGov OpenShift platform users, and provide immediate feedback on their project's compliance to BCGov best practices.

[Definition of Done]

- [x] MVP solution built, tested, reviewed
- [x] Solution documented
- [x] Implemented into LAB cluster to confirm functionality
- [x] Presented to BCGov platform team
- [x] Add tooltips with a link to an online doc somewhere that explains what the setting is for and also includes best practices for the setting value to help developers understand app settings in OpenShift

**Comment by michaelshire** [comment]
@lukegonis can you assign to me, put this into the next sprint?  I think its about an 8.

**Comment by michaelshire** [comment]
MVP complete, tested (externally to bcgov).  Initial review scheduled for 2021-10-20.
Starting documentation of the solution.

**Comment by Nicole-Huard** [comment]
Arctiq team to connect wit Alex Carmichael and send the PR for the header & footer @Markieta

**Comment by Markieta** [comment]
PR created: [Adding BC Gov header, footer, styling, and setting default log destination to stdout #18](https://github.com/bcgov/AppAssessment/pull/18)

@ShovelHand I kindly appreciate your review.

This PR includes the header and footer as per the bcgov design, however, the footer hyperlinks currently do not have any references.

I also do not have write access to the [bcgov/AppAssessment](https://github.com/bcgov/AppAssessment) repo, I will need someone to provide me the same level of access to this repo as **michaelshire** as I am taking over for his work here.

**Comment by Nicole-Huard** [comment]
@mitovskaol Following up on Chris's PR, linked above ^^, to see if there is any further action required from Arctiq.  Thanks!

**Comment by mitovskaol** [comment]
@Nicole-Huard  As per the discussion in the Sprint planning,  the last deliverable for Actiq f would be to do add tooltips that explain the purpose of each metrics in the outcome report in the Assessment app. The rest of the work on the app will be delivered by the BC Gov team.

**Comment by Markieta** [comment]
@mitovskaol sorry, to be clear, my PR above also includes the tooltips for each metric in the report.

**Comment by mitovskaol** [comment]
@Markieta I've added you to the team @bcgov/arctiq that has Admin access to the security pipelines and the AppAssessment repos. Please let me know if you have any problems with accessing the repos.

**Comment by Markieta** [comment]
Thanks @mitovskaol , PR merged.

Someone with access will need to execute: `oc start-build -n bcgov appassessment` in order to rebuild the image.

This work includes the bcgov **styling** and **tooltips** and is complete from my perspective. Please let me know if anything else is required from Arctiq.

**Comment by mitovskaol** [comment]
@ShovelHand  Please see the above,  you will most likely need to pull the new changes from the PR into your local environment.

**Comment by Nicole-Huard** [comment]
@mitovskaol since the DOD is complete for this ticket, and there is a new ticket for Alex's [UI updates](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1826) can we close this issue?
