### ISSUE TITLE
OPS Manager Deliverables

### ISSUE THREAD

**Issue by sbathgate** [bcgov/devhub-app-web#1679]
- [x] Document an operational support model for critical  Platform Services including 7-7000 script, escalation procedures with DXC and vendors, Platform Services Team’s rotating on-call schedules, etc. 

- [x] Ensure that each tool has:  a support lead and a backup lead assigned (maintain uninterrupted coverage in a support calendar), comes with a troubleshooting guide and an escalation procedure (has an operational support template developed) 

- [x] Ensure that all essential Platform Services and Tools are monitored across all Platform production clusters and have 24/7 support   

- [x] Ensure all tools and the Platform itself follow the government’s security governance and have STRA/PIA completed
